version: '3'

services:
  langfuse-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=langfuse
    ports:
      - 5432:5432
    volumes:
      - langfuse-data:/var/lib/postgresql/data

  langfuse-web:
    image: langfuse/langfuse:2.90.0
    depends_on:
      - langfuse-db
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@langfuse-db:5432/langfuse
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt

volumes:
  langfuse-data:
